export const ERROR_MESSAGES = {
  INTERNAL_SERVER_ERROR: "Something went wrong",
  INVALID_CREDENTIALS: "Invalid email or password",
  USER_NOT_FOUND: "User not found",
  USER_ALREADY_EXISTS: "User already exists",
  EMAIL_ALREADY_EXISTS: "Email already exists",
  USERNAME_ALREADY_EXISTS: "Username already exists",
  ACCOUNT_DISABLED: "Account disabled",
  ACCOUNT_NOT_VERIFIED: "Account not verified",
  CONTACT_ALREADY_EXISTS: "Contact already exists",
  CONTACT_NOT_FOUND: "Contact not found",
  CANNOT_ADD_SELF: "You cannot add yourself as a contact",
  CANNOT_BLOCK_SELF: "You cannot block yourself",
  CONVERSATION_NOT_FOUND: "Conversation not found",
  GROUP_NOT_FOUND: "Group not found",
  MESSAGE_NOT_FOUND: "Message not found",
  PARTICIPANT_NOT_FOUND: "Participant not found",
  UNAUTHORIZED: "Unauthorized access",
  INVALID_TOKEN: "Invalid token",
  TOKEN_EXPIRED: "Token expired",
  FORBIDDEN: "Access denied",
  ROUTE_NOT_FOUND: "Route not found",
  VALIDATION_FAILED: "Validation failed",
};
